---
- name: Setup server
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update-cache: yes

    - name: Install system tools
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Copy docker-compose.yml to server
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Tear down exisiting containers
      command: docker-compose down
      args:
        chdir: /home/ubuntu
      ignore_errors: yes

    - name: Start App and DB
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu

    - name: Wait for database to initialise
      wait_for:
        timeout: 20

    - name: Create database tables
      command: docker-compose exec -T app sh -c "cd src && python -c 'from app import app, db; app.app_context().push(); db.create_all()'"
      register: db_setup
      retries: 3
      delay: 10
      until: db_setup.rc == 0
      ignore_errors: yes

    - name: Copy prometheus configuration
      copy:
        src: prometheus.yml
        dest: /home/ubuntu/prometheus.yml

    - name: Run Promethues Container
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus
        state: started
        restart_policy: always
        ports:
          - "9090:9090"
        volumes:
          - /home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
          - name: app_network

    - name: Run Grafana Container
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
        networks:
          - name: app_network
