---
- name: Setup server
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update-cache: yes

    - name: Install system tools
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Copy docker-compose.yml to server
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Tear down exisiting containers
      command: docker-compose down
      args:
        chdir: /home/ubuntu
      ignore_errors: yes

    - name: Start App and DB
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu
